# Generated by Django 4.2 on 2025-09-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitiosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('playa', 'Playa'), ('ciudad_patrimonial', 'Ciudad Patrimonial'), ('hospedaje', 'Hospedaje')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.TextField(blank=True)),
                ('latitud', models.FloatField(blank=True, null=True)),
                ('longitud', models.FloatField(blank=True, null=True)),
                ('precio_aprox', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento')),
            ],
        ),
    ]
