# Generated by Django 4.2 on 2025-09-07 06:00
from django.db import migrations


def cargar_sitios_turisticos(apps, schema_editor):
    SitiosTuristicos = apps.get_model('SitiosTuristicos', 'SitiosTuristicos')
    Departamento = apps.get_model('Departamento', 'Departamento')

    # Obtener departamentos por nombre
    rivas = Departamento.objects.get(nombre='Rivas')
    carazo = Departamento.objects.get(nombre='Carazo')
    chinandega = Departamento.objects.get(nombre='Chinandega')
    raas = Departamento.objects.get(nombre='Región Autónoma de la Costa Caribe Sur (RAAS)')
    granada = Departamento.objects.get(nombre='Granada')
    leon = Departamento.objects.get(nombre='León')
    masaya = Departamento.objects.get(nombre='Masaya')
    esteli = Departamento.objects.get(nombre='Estelí')
    chontales = Departamento.objects.get(nombre='Chontales')
    nueva_segovia = Departamento.objects.get(nombre='Nueva Segovia')
    madriz = Departamento.objects.get(nombre='Madriz')
    raan = Departamento.objects.get(nombre='Región Autónoma de la Costa Caribe Norte (RAAN)')

    sitios = [
        # PLAYAS
        {'nombre': 'Playa Maderas', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Paraíso para surfistas con olas consistentes y ambiente bohemio. Arena oscura y paisajes espectaculares.',
         'latitud': 11.4486, 'longitud': -86.1333},
        {'nombre': 'Playa Hermosa', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Playa familiar de aguas tranquilas y arena clara. Ideal para nadar y disfrutar en familia.',
         'latitud': 11.4012, 'longitud': -86.1315},
        {'nombre': 'Playa El Coco', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Aguas cristalinas y tranquilas perfectas para snorkeling. Palmeras y ambiente relajado.',
         'latitud': 11.3897, 'longitud': -86.1218},
        {'nombre': 'Playa Popoyo', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Olas poderosas para surfistas avanzados. Playa extensa con espectaculares atardeceres.',
         'latitud': 11.4736, 'longitud': -86.1569},
        {'nombre': 'Playa Marsella', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Caleta privada cerca de San Juan del Sur. Aguas tranquilas y entorno natural preservado.',
         'latitud': 11.2175, 'longitud': -86.1297},
        {'nombre': 'Playa La Flor', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Reserva natural donde miles de tortugas desovan cada año. Espectáculo de la naturaleza.',
         'latitud': 11.1486, 'longitud': -86.1358},
        {'nombre': 'Playa El Ostional', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Pueblo pesquero auténtico con playa virgen. Ideal para experiencias culturales reales.',
         'latitud': 11.1253, 'longitud': -86.1589},
        {'nombre': 'Playa Majagual', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Una de las playas más largas de San Juan del Sur. Perfecta para caminatas y deportes playeros.',
         'latitud': 11.2356, 'longitud': -86.1189},
        {'nombre': 'Playa Remanso', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Playa semi-privada con excelentes olas para surf. Restaurantes playeros con vista al océano.',
         'latitud': 11.2289, 'longitud': -86.1225},
        {'nombre': 'Playa El Yankee', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Playa rodeada de colinas verdes. Ambiente tranquilo y bueno para surf principiante.',
         'latitud': 11.2422, 'longitud': -86.1158},
        {'nombre': 'Playa Guasacate', 'tipo': 'playa', 'departamento': rivas,
         'descripcion': 'Comunidad de surfistas internacionales. Olas consistentes y vida comunitaria única.',
         'latitud': 11.4614, 'longitud': -86.1492},
        {'nombre': 'Playa Amarilla', 'tipo': 'playa', 'departamento': carazo,
         'descripcion': 'Nombre por la arena amarillenta. Popular entre locales los fines de semana.',
         'latitud': 11.7892, 'longitud': -86.4514},
        {'nombre': 'Playa Casares', 'tipo': 'playa', 'departamento': carazo,
         'descripcion': 'Playa de rocas volcánicas y piscinas naturales. Ideal para exploración y fotografía.',
         'latitud': 11.8014, 'longitud': -86.4389},
        {'nombre': 'Playa La Boquita', 'tipo': 'playa', 'departamento': carazo,
         'descripcion': 'Playa urbana con restaurantes de mariscos frescos. Ambiente festivo los domingos.',
         'latitud': 11.7758, 'longitud': -86.4267},
        {'nombre': 'Playa Huehuete', 'tipo': 'playa', 'departamento': chinandega,
         'descripcion': 'A los pies del volcán Cosigüina. Aguas termales y paisaje volcánico único.',
         'latitud': 12.9825, 'longitud': -87.5689},
        {'nombre': 'Playa Jiquilillo', 'tipo': 'playa', 'departamento': chinandega,
         'descripcion': 'Pueblo pesquero auténtico. Observación de aves y puestas de sol espectaculares.',
         'latitud': 12.7458, 'longitud': -87.4514},
        {'nombre': 'Playa Aserradores', 'tipo': 'playa', 'departamento': chinandega,
         'descripcion': 'Olas de clase mundial. sede de competencias internacionales de surf.', 'latitud': 12.5689,
         'longitud': -87.3214},
        {'nombre': 'Playa Punta Ñata', 'tipo': 'playa', 'departamento': raas,
         'descripcion': 'Arena blanca y aguas turquesas del Caribe. Cultura afrodescendiente y garífuna.',
         'latitud': 12.1856, 'longitud': -83.0514},
        {'nombre': 'Playa Corn Island', 'tipo': 'playa', 'departamento': raas,
         'descripcion': 'Isla caribeña con cultura criolla. Buceo con tortugas and langostas frescas.',
         'latitud': 12.1683, 'longitud': -83.0417},
        {'nombre': 'Playa Little Corn Island', 'tipo': 'playa', 'departamento': raas,
         'descripcion': 'Isla sin automóviles. Paraíso para buceo y desconexión total.', 'latitud': 12.3458,
         'longitud': -83.0014},

        # CIUDADES PATRIMONIALES
        {'nombre': 'Granada', 'tipo': 'ciudad_patrimonial', 'departamento': granada,
         'descripcion': 'La Gran Sultana, joya colonial con calles coloridas, iglesias históricas y frente al lago Cocibolca.',
         'latitud': 11.9340, 'longitud': -85.9560},
        {'nombre': 'León', 'tipo': 'ciudad_patrimonial', 'departamento': leon,
         'descripcion': 'Ciudad universitaria y revolucionaria. Hogar de la más grande catedral de Centroamérica.',
         'latitud': 12.4340, 'longitud': -86.8784},
        {'nombre': 'Masaya', 'tipo': 'ciudad_patrimonial', 'departamento': masaya,
         'descripcion': 'Ciudad de las flores y capital del folklore nicaragüense. Famosa por su mercado de artesanías.',
         'latitud': 11.9744, 'longitud': -86.0944},
        {'nombre': 'Estelí', 'tipo': 'ciudad_patrimonial', 'departamento': esteli,
         'descripcion': 'Ciudad diamante en el norte de Nicaragua. Conocida por producción de tabaco y murales.',
         'latitud': 13.0916, 'longitud': -86.3535},
        {'nombre': 'Juigalpa', 'tipo': 'ciudad_patrimonial', 'departamento': chontales,
         'descripcion': 'Ciudad ganadera del corazón de Chontales. Museo arqueológico con estatuas precolombinas.',
         'latitud': 12.1000, 'longitud': -85.3667},
        {'nombre': 'Ocotal', 'tipo': 'ciudad_patrimonial', 'departamento': nueva_segovia,
         'descripcion': 'Ciudad fronteriza con Honduras en las montañas. Clima fresco y producción de café.',
         'latitud': 13.6333, 'longitud': -86.4833},
        {'nombre': 'Somoto', 'tipo': 'ciudad_patrimonial', 'departamento': madriz,
         'descripcion': 'Puerta de entrada al Cañón de Somoto. Ciudad fronteriza con rica historia.',
         'latitud': 13.4833, 'longitud': -86.5833},
        {'nombre': 'Rivas', 'tipo': 'ciudad_patrimonial', 'departamento': rivas,
         'descripcion': 'Ciudad de mangos y cruce de caminos. Conecta el Pacífico con el lago Cocibolca.',
         'latitud': 11.4333, 'longitud': -85.8333},
        {'nombre': 'Bluefields', 'tipo': 'ciudad_patrimonial', 'departamento': raas,
         'descripcion': 'Capital de la Costa Caribe Sur. Cultura criolla-caribeña única y gastronomía.',
         'latitud': 12.0167, 'longitud': -83.7667},
        {'nombre': 'Puerto Cabezas', 'tipo': 'ciudad_patrimonial', 'departamento': raan,
         'descripcion': 'Capital de la Costa Caribe Norte. Cultura miskita vibrante y playas vírgenes.',
         'latitud': 14.0333, 'longitud': -83.3833},
    ]

    for sitio_data in sitios:
        SitiosTuristicos.objects.get_or_create(**sitio_data)


class Migration(migrations.Migration):
    dependencies = [
        ('SitiosTuristicos', '0001_initial'),
        ('Departamento', '0002_auto_20250908_0016'),  # Asegúrate que esta migración existe
    ]

    operations = [
        migrations.RunPython(cargar_sitios_turisticos),
    ]