# Generated by Django 4.2 on 2025-09-07 06:00
from django.db import migrations


def cargar_hospedajes(apps, schema_editor):
    SitiosTuristicos = apps.get_model('SitiosTuristicos', 'SitiosTuristicos')
    Departamento = apps.get_model('Departamento', 'Departamento')

    # Obtener departamentos por nombre
    granada = Departamento.objects.get(nombre='Granada')
    leon = Departamento.objects.get(nombre='León')
    esteli = Departamento.objects.get(nombre='Estelí')
    masaya = Departamento.objects.get(nombre='Masaya')
    rivas = Departamento.objects.get(nombre='Rivas')
    managua = Departamento.objects.get(nombre='Managua')
    matagalpa = Departamento.objects.get(nombre='Matagalpa')
    chontales = Departamento.objects.get(nombre='Chontales')
    raas = Departamento.objects.get(nombre='Región Autónoma de la Costa Caribe Sur (RAAS)')

    hospedajes = [
        {'nombre': 'Hotel Convento San Francisco', 'tipo': 'hospedaje', 'departamento': granada,
         'descripcion': 'Hotel boutique en convento histórico restaurado. Patios coloniales y ubicación privilegiada.',
         'direccion': 'Calle El Caimito, frente al Parque Central, Granada', 'latitud': 11.9345, 'longitud': -85.9558,
         'precio_aprox': 120.00},
        {'nombre': 'Hotel Plaza Colón', 'tipo': 'hospedaje', 'departamento': granada,
         'descripcion': 'Lujo colonial en pleno parque central. Terraza con vista a la catedral y servicio cinco estrellas.',
         'direccion': 'Plaza de la Independencia, Granada', 'latitud': 11.9339, 'longitud': -85.9559,
         'precio_aprox': 150.00},
        {'nombre': 'Hotel El Virrey', 'tipo': 'hospedaje', 'departamento': leon,
         'descripcion': 'Hotel familiar en corazón de León. Patio central con fuente y proximidad a catedral y museos.',
         'direccion': 'Calle Central, León', 'latitud': 12.4345, 'longitud': -86.8782, 'precio_aprox': 65.00},
        {'nombre': 'Hotel La Perla', 'tipo': 'hospedaje', 'departamento': leon,
         'descripcion': 'Icono leonés con arquitectura neoclásica. Restaurante reconocido y ambiente elegante.',
         'direccion': 'Avenida Central, León', 'latitud': 12.4342, 'longitud': -86.8788, 'precio_aprox': 85.00},
        {'nombre': 'Hotel Patio del Malinche', 'tipo': 'hospedaje', 'departamento': esteli,
         'descripcion': 'Encanto norteño en Estelí. Jardines interiores y proximidad a fábricas de puros.',
         'direccion': 'Barrio San Juan, Estelí', 'latitud': 13.0918, 'longitud': -86.3532, 'precio_aprox': 55.00},
        {'nombre': 'Hotel Los Altos', 'tipo': 'hospedaje', 'departamento': esteli,
         'descripcion': 'Vista panorámica de Estelí. Moderno con comodidades empresariales y restaurante gourmet.',
         'direccion': 'Loma de Los Altos, Estelí', 'latitud': 13.0922, 'longitud': -86.3538, 'precio_aprox': 75.00},
        {'nombre': 'Hotel Casa Naranja', 'tipo': 'hospedaje', 'departamento': masaya,
         'descripcion': 'Colorido hospedaje masaya. Terraza con vista al volcán y mercado de artesanías a pasos.',
         'direccion': 'Calle Calvario, Masaya', 'latitud': 11.9746, 'longitud': -86.0942, 'precio_aprox': 45.00},
        {'nombre': 'Hotel Ivania\'s', 'tipo': 'hospedaje', 'departamento': rivas,
         'descripcion': 'Hospitalidad familiar en San Juan del Sur. Jardín tropical y a dos cuadras de la playa.',
         'direccion': 'Avenida del Surf, San Juan del Sur', 'latitud': 11.2528, 'longitud': -86.8525,
         'precio_aprox': 40.00},
        {'nombre': 'Pelican Eyes Resort', 'tipo': 'hospedaje', 'departamento': rivas,
         'descripcion': 'Lujo con vista al océano. Villas privadas, piscinas infinitas y spa de clase mundial.',
         'direccion': 'Cererto La Vista, San Juan del Sur', 'latitud': 11.2532, 'longitud': -86.8528,
         'precio_aprox': 200.00},
        {'nombre': 'Hotel Morgan\'s Rock', 'tipo': 'hospedaje', 'departamento': rivas,
         'descripcion': 'Ecolodge de lujo en playa privada. Bungalows sobre acantilados y conservación de tortugas.',
         'direccion': 'Playa Ocotal, Rivas', 'latitud': 11.1489, 'longitud': -86.1362, 'precio_aprox': 300.00},
        {'nombre': 'Hotel Barceló Montelimar', 'tipo': 'hospedaje', 'departamento': managua,
         'descripcion': 'Todo incluido en playa del Pacífico. Actividades familiares, golf y entretenimiento nocturno.',
         'direccion': 'Carretera a Masachapa, Managua', 'latitud': 11.7895, 'longitud': -86.4521,
         'precio_aprox': 180.00},
        {'nombre': 'Hotel Camino Real', 'tipo': 'hospedaje', 'departamento': managua,
         'descripcion': 'Negocios y lujo en capital. Centro de convenciones y proximidad a zona comercial.',
         'direccion': 'Carretera a Masaya, Managua', 'latitud': 12.1367, 'longitud': -86.2514, 'precio_aprox': 130.00},
        {'nombre': 'Hotel Selva Negra', 'tipo': 'hospedaje', 'departamento': matagalpa,
         'descripcion': 'Ecolodge en montañas de Matagalpa. Cabañas en bosque nuboso y tour de café orgánico.',
         'direccion': 'Kilómetro 140, Matagalpa', 'latitud': 12.9833, 'longitud': -85.9167, 'precio_aprox': 90.00},
        {'nombre': 'Hotel Sollentuna Hammock', 'tipo': 'hospedaje', 'departamento': granada,
         'descripcion': 'Hospedaje ecológico en Ometepe. Hamacas gigantes y vista al volcán Concepción.',
         'direccion': 'Playa Santo Domingo, Isla de Ometepe', 'latitud': 11.5083, 'longitud': -85.5833,
         'precio_aprox': 35.00},
        {'nombre': 'Hotel Charco Verde', 'tipo': 'hospedaje', 'departamento': granada,
         'descripcion': 'Reserva natural en Ometepe. Cabañas frente a laguna y avistamiento de aves endémicas.',
         'direccion': 'Reserva Charco Verde, Ometepe', 'latitud': 11.4667, 'longitud': -85.5667, 'precio_aprox': 60.00},
        {'nombre': 'Hotel Hacienda Mérida', 'tipo': 'hospedaje', 'departamento': granada,
         'descripcion': 'Hostal con historia en Ometepe. Museo petroglifos y base para escalar volcanes.',
         'direccion': 'Puerto de Mérida, Ometepe', 'latitud': 11.5167, 'longitud': -85.6167, 'precio_aprox': 25.00},
        {'nombre': 'Hotel Caribbean Dream', 'tipo': 'hospedaje', 'departamento': raas,
         'descripcion': 'Sabor caribeño en Bluefields. Decoración criolla y música live los fines de semana.',
         'direccion': 'Barrio Punta Fría, Bluefields', 'latitud': 12.0169, 'longitud': -83.7669, 'precio_aprox': 50.00},
        {'nombre': 'Hotel Paraíso Club', 'tipo': 'hospedaje', 'departamento': raas,
         'descripcion': 'Bungalows frente al mar Caribe. Buceo y snorkeling en arrecifes de coral.',
         'direccion': 'South End, Corn Island', 'latitud': 12.1685, 'longitud': -83.0419, 'precio_aprox': 110.00},
        {'nombre': 'Hotel Casa Canadiense', 'tipo': 'hospedaje', 'departamento': chontales,
         'descripcion': 'Hospitalidad canadiense-nicaragüense. Jardín botánico y tour a haciendas ganaderas.',
         'direccion': 'Salida a Acoyapa, Juigalpa', 'latitud': 12.1002, 'longitud': -85.3669, 'precio_aprox': 40.00},
        {'nombre': 'Hotel Altagracia', 'tipo': 'hospedaje', 'departamento': rivas,
         'descripcion': 'Tradición rivense por generaciones. Parque central y comida típica del Pacífico.',
         'direccion': 'Frente a parque central, Rivas', 'latitud': 11.4335, 'longitud': -85.8335,
         'precio_aprox': 30.00},
    ]

    for hospedaje_data in hospedajes:
        SitiosTuristicos.objects.get_or_create(**hospedaje_data)


class Migration(migrations.Migration):
    dependencies = [
        ('SitiosTuristicos', '0002_auto_20250908_0023'),  # Después de cargar sitios turísticos
        ('Departamento', '0002_auto_20250908_0016'),
    ]

    operations = [
        migrations.RunPython(cargar_hospedajes),
    ]
