# Generated by Django 4.2 on 2025-09-22 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SitiosTuristicos', '0004_auto_20250921_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitiosturisticos',
            name='tipo',
            field=models.CharField(choices=[('playa', 'Playa'), ('ciudad_patrimonial', 'Ciudad Patrimonial'), ('hospedaje', 'Hospedaje'), ('reserva_natural', 'Reserva Natural')], max_length=30),
        ),
    ]
