# Generated by Django 4.2 on 2025-09-22 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Departamento', '0002_auto_20250908_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventosTuristicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Departamento.departamento')),
            ],
            options={
                'ordering': ['mes', 'departamento__nombre'],
            },
        ),
    ]
