# Generated by Django 4.2 on 2025-09-07 06:00
from django.db import migrations
from App.EventosTuristicos.models import EventosTuristicos


def cargar_eventos_turisticos(apps, schema_editor):
    EventosTuristicos = apps.get_model('EventosTuristicos', 'EventosTuristicos')
    Departamento = apps.get_model('Departamento', 'Departamento')

    # Obtener departamentos por ID (según tu JSON)
    # Estos son los IDs que usaste en tu JSON:
    # 6 = Granada, 11 = Masaya, 8 = León, 10 = Managua, 13 = Nueva Segovia, 5 = Estelí, 14 = Río San Juan

    eventos_data = [
        {
            "nombre": "Festival de Cultura Viva",
            "descripcion": "Muestras de música, danzas y artesanías tradicionales en espacios al aire libre.",
            "departamento_id": 6,  # Granada
            "mes": 11
        },
        {
            "nombre": "Semana de la Gastronomía de Masaya",
            "descripcion": "Gastronomía local, ferias de comidas típicas y recorridos culinarios.",
            "departamento_id": 11,  # Masaya
            "mes": 8
        },
        {
            "nombre": "Encuentro de Avistamiento de Aves Laguna de Apoyo",
            "descripcion": "Salida guiada para observar aves migratorias y residentes alrededor de la laguna.",
            "departamento_id": 11,  # Masaya
            "mes": 3
        },
        {
            "nombre": "Concierto de Música Nicaragüense en León",
            "descripcion": "Concierto al aire libre con artistas locales tradicionales y contemporáneos.",
            "departamento_id": 8,  # León
            "mes": 7
        },
        {
            "nombre": "Tour Nocturno al Volcán Masaya",
            "descripcion": "Visita guiada al cráter y vistas nocturnas, espectáculo de fuego volcánico.",
            "departamento_id": 11,  # Masaya
            "mes": 12
        },
        {
            "nombre": "Festival Internacional de Jazz Managua",
            "descripcion": "Artistas invitados nacionales e internacionales, noche de jazz bajo las estrellas.",
            "departamento_id": 10,  # Managua
            "mes": 2
        },
        {
            "nombre": "Circuito de Senderismo y Naturaleza Jinotega",
            "descripcion": "Recorridos guiados por rutas naturales, cascadas y miradores en Jinotega.",
            "departamento_id": 13,  # Nueva Segovia
            "mes": 4
        },
        {
            "nombre": "Feria del Café en Estelí",
            "descripcion": "Degustaciones, exposiciones y actividades relacionadas al café y su producción.",
            "departamento_id": 5,  # Estelí
            "mes": 10
        },
        {
            "nombre": "Temporada de Aves Migratorias en Río San Juan",
            "descripcion": "Observación guiada de aves migratorias, colaboración con reservas locales.",
            "departamento_id": 14,  # Río San Juan
            "mes": 3
        },
        {
            "nombre": "Festival de Cine y Cultura Nica",
            "descripcion": "Proyecciones de cine nacional, música local y expresión artística.",
            "departamento_id": 10,  # Managua
            "mes": 5
        }
    ]

    for evento_data in eventos_data:
        # Usamos get_or_create para evitar duplicados
        EventosTuristicos.objects.get_or_create(
            nombre=evento_data['nombre'],
            defaults={
                'descripcion': evento_data['descripcion'],
                'departamento_id': evento_data['departamento_id'],
                'mes': evento_data['mes']
            }
        )


class Migration(migrations.Migration):
    dependencies = [
        ('EventosTuristicos', '0001_initial'),  # La migración inicial de Eventos
        ('Departamento', '0002_auto_20250908_0016'),  # Asegura que los departamentos estén cargados
    ]

    operations = [
        migrations.RunPython(cargar_eventos_turisticos),
    ]
