# Generated by Django 4.2 on 2025-09-27 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuarioGuia', '0001_initial'),
        ('UsuarioTuristico', '0001_initial'),
        ('SitiosTuristicos', '0005_alter_sitiosturisticos_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reserva', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('duracion_horas', models.IntegerField(default=4)),
                ('numero_personas', models.IntegerField(default=1)),
                ('precio_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comision_plataforma', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmada', 'Confirmada'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta Crédito/Débito'), ('transferencia', 'Transferencia'), ('paypal', 'PayPal')], max_length=20)),
                ('requisitos_especiales', models.TextField(blank=True)),
                ('punto_encuentro', models.CharField(blank=True, max_length=200)),
                ('codigo_confirmacion', models.CharField(blank=True, max_length=6)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('comentario', models.TextField(blank=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='UsuarioGuia.guiaturistico')),
                ('sitio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SitiosTuristicos.sitiosturisticos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='UsuarioTuristico.usuarioturistico')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ServicioComplementario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('transporte', 'Transporte'), ('alimentacion', 'Alimentación'), ('equipo', 'Equipo Especializado'), ('alojamiento', 'Alojamiento'), ('seguro', 'Seguro de Viaje')], max_length=20)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicioReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_adicionales', to='Reservas.reserva')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservas.serviciocomplementario')),
            ],
            options={
                'unique_together': {('reserva', 'servicio')},
            },
        ),
    ]
