# Generated by Django 4.2 on 2025-09-07 06:00 (o la fecha que te aparezca)
from django.db import migrations

def cargar_departamentos(apps, schema_editor):
    Departamento = apps.get_model('Departamento', 'Departamento')
    lista_departamentos = [
        "Boaco", "Carazo", "Chinandega", "Chontales", "Estelí",
        "Granada", "Jinotega", "León", "Madriz", "Managua",
        "Masaya", "Matagalpa", "Nueva Segovia", "Río San Juan", "Rivas",
        "Región Autónoma de la Costa Caribe Norte (RAAN)",
        "Región Autónoma de la Costa Caribe Sur (RAAS)"
    ]
    for nombre in lista_departamentos:
        Departamento.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        # Esto depende de cómo se llame tu migración inicial, AJUSTALO:
        ('Departamento', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(cargar_departamentos),
    ]
