# Generated by Django 4.2 on 2025-09-27 08:13

import Usuarios.UsuarioGuia.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UsuarioTuristico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTuristico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Sexo')),
                ('cedula', models.CharField(max_length=16, unique=True, verbose_name='Cédula')),
                ('foto_cedula_frontal', models.ImageField(upload_to=Usuarios.UsuarioGuia.models.upload_to_identificacion, verbose_name='Foto Cédula Frontal')),
                ('foto_cedula_reverso', models.ImageField(upload_to=Usuarios.UsuarioGuia.models.upload_to_identificacion, verbose_name='Foto Cédula Reverso')),
                ('certificado_guia', models.FileField(blank=True, null=True, upload_to=Usuarios.UsuarioGuia.models.upload_to_certificaciones, verbose_name='Certificado de Guía Turístico')),
                ('licencia_conducir', models.FileField(blank=True, null=True, upload_to=Usuarios.UsuarioGuia.models.upload_to_certificaciones, verbose_name='Licencia de Conducir (opcional)')),
                ('idiomas', models.CharField(help_text='Ej: Español, Inglés, Francés. Separados por comas', max_length=100)),
                ('especialidades', models.CharField(blank=True, help_text='Ej: Avistamiento de aves, Historia colonial, Surf, etc.', max_length=200)),
                ('experiencia', models.TextField(help_text='Describe tu experiencia como guía, estudios relacionados, etc.', verbose_name='Experiencia y formación')),
                ('anos_experiencia', models.IntegerField(default=0, verbose_name='Años de experiencia')),
                ('precio_por_hora', models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Precio por hora (USD)')),
                ('precio_por_dia', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Precio por día completo (USD)')),
                ('zonas_cobertura', models.CharField(default='Granada', help_text='Departamentos o ciudades donde trabajas. Ej: Granada, Masaya, Ometepe', max_length=300)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('telefono_whatsapp', models.CharField(blank=True, max_length=15)),
                ('enlace_facebook', models.URLField(blank=True)),
                ('enlace_instagram', models.URLField(blank=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_guia', to='UsuarioTuristico.usuarioturistico')),
            ],
            options={
                'verbose_name': 'Guía Turístico',
                'verbose_name_plural': 'Guías Turísticos',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
